vagrant_box: bento/centos-8
vagrant_box_version: "202002.04.0"
vagrant_ip: 192.168.80.
vagrant_hostname: vagrant
vagrant_memory: 1024
vagrant_directory: /vagrant
vagrant_cpu: 1
vagrant_box_check_update: false
vagrant_domain_name: ipa.bmxinit.ga
