vagrant_box: centos/7
vagrant_box_version: "1804.02"
vagrant_ip: 192.168.80.
vagrant_hostname: vagrant
vagrant_memory: 1024
vagrant_directory: /vagrant
vagrant_cpu: 1
vagrant_box_check_update: false
vagrant_domain_name: test.local
